### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by xmrig** [xmrig/xmrig#106]
### Roadmap for next releases

- [x] [HTTP API](https://github.com/xmrig/xmrig/wiki/API) for cpu/nvidia miners, done in dev branch #6.
- [x] Proxy updates
  - [x] [HTTP API](https://github.com/xmrig/xmrig-proxy/wiki/API)
  - [x] Access log
  - [x] Per worker statistics
  - [x] Custom worker diff
  - [x] Donation
- [x] Triple release 2.4 (cpu/nvidia/proxy)
  - [x] https://github.com/xmrig/xmrig/milestone/1
  - [x] https://github.com/xmrig/xmrig-nvidia/milestone/1
- [x] [AMD/OpenCL miner](https://github.com/xmrig/xmrig-amd)
- [x] ARM CPUs support #94
  - [x] ARMv8 support
  - [x] ARMv7 support #216
  - [ ] Android support #11 ***postponed***
- [x] #434 Release v2.5 with upcoming March 28 Monero PoW change.
- [x] Proper NUMA support #86
- [ ] Unified monitoring center (SPA+HTTP API) for miners and proxy.

### Other TODO
- [x] Extended low power mode for L4 cache #255
- [x] SSL/TLS support for proxy and miners. [#8](https://github.com/xmrig/xmrig-proxy/issues/8)
- [ ] HTTP/SOCKS proxy support #186
- [x] Dynamic (without restart) proxy settings change https://github.com/xmrig/xmrig-proxy/issues/40

**Comment by chaoscraig** [comment]
Hey, this team red miner is running with muuuch lower power. Are the xm rig dev's working on this?
